version: '3.3'
 
services:
  angular:
    build: .
    restart: always
    volumes:
     - ./dist/erf:/usr/share/nginx/html:ro
    ports:
     - 80:80
 
networks:
  default:
    external:
      name: erf